#ifndef ENGINE_MOUSEBUTTONCODES_H
#define ENGINE_MOUSEBUTTONCODES_H

// From glfw3.h
#define DM_MOUSE_BUTTON_1         0
#define DM_MOUSE_BUTTON_2         1
#define DM_MOUSE_BUTTON_3         2
#define DM_MOUSE_BUTTON_4         3
#define DM_MOUSE_BUTTON_5         4
#define DM_MOUSE_BUTTON_6         5
#define DM_MOUSE_BUTTON_7         6
#define DM_MOUSE_BUTTON_8         7
#define DM_MOUSE_BUTTON_LAST      DM_MOUSE_BUTTON_8
#define DM_MOUSE_BUTTON_LEFT      DM_MOUSE_BUTTON_1
#define DM_MOUSE_BUTTON_RIGHT     DM_MOUSE_BUTTON_2
#define DM_MOUSE_BUTTON_MIDDLE    DM_MOUSE_BUTTON_3

#endif //ENGINE_MOUSEBUTTONCODES_H
